config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments

  root :to => redirect('/ideas')
  resources :ideas

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :idea
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	has_many :comments
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Atributo criado com sucesso.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Atributo atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Atributo excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :idea_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Produto modificado com sucesso.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Produto excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
      @comment = @idea.comments.build
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
    <%= f.hidden_field :idea_id %>
  </div>
  <div class="field">
    <%= f.label :idea_id %><br>
    <%= f.number_field :idea_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editar Atributo</h1>

<%= render 'form' %>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Ver', @comment %></button> |
<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Voltar', comments_path %></button>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Atributos</h1>
<button type="button" class="btn btn-primary btn-lg btn-block"><%= link_to 'Adicionar Novo Atributo', new_comment_path %></button>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Tipo de Atributo</th>
      <th>Descição</th>
      <th>Identificação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.idea_id %></td>
        <td><button type="button" class="btn btn-primary btn-xs"><%= link_to 'Ver', comment %></button></td>
        <td><button type="button" class="btn btn-primary btn-xs"><%= link_to 'Editar', edit_comment_path(comment) %></button></td>
        <td><button type="button" class="btn btn-primary btn-xs"><%= link_to 'Excluir', comment, method: :delete, data: { confirm: 'Você tem certeza de que deseja excluir permanentemente este atributo?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-primary btn-lg btn-block"><%= link_to 'Adicionar Novo Atributo', new_comment_path %></button>

app/views/comments/new.html.erb
<h1>Novo Atributo</h1>

<%= render 'form' %>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Voltar', comments_path %></button>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo de Atributo:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Identificação:</strong>
  <%= @comment.idea_id %>
</p>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Editar', edit_comment_path(@comment) %></button> |
<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Voltar', comments_path %></button>

app/views/ideas/_form.html.erb
<%= form_for(@idea, :html => { :multipart => true }) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form' %>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Ver', @idea %></button> |
<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Voltar', ideas_path %></button>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Produtos</h1>
<button type="button" class="btn btn-primary btn-lg btn-block"><%= link_to 'Adiconar Novo Produto', new_idea_path %></button>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Imágem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= image_tag idea.picture_url(:thumb) if idea.picture? %></td>
        <td><button type="button" class="btn btn-primary btn-xs"><%= link_to 'Ver', idea %></td></button>
        <td><button type="button" class="btn btn-primary btn-xs"><%= link_to 'Editar', edit_idea_path(idea) %></td></button>
        <td><button type="button" class="btn btn-primary btn-xs"><%= link_to 'Excluir', idea, method: :delete, data: { confirm: 'Você tem certeza de que deseja excluir este comentário permanentemente?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<button type="button" class="btn btn-primary btn-lg btn-block"><%= link_to 'Adiconar Novo Produto', new_idea_path %></button>

app/views/ideas/new.html.erb
<h1>Novo Produto</h1>

<%= render 'form' %>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Voltar', ideas_path %></button>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Imágem:</strong>
  <%= image_tag(@idea.picture_url, :width => 600) if @idea.picture.present? %>
  <h3>Atributos:</h3>
  <% @idea.comments.each do |comment| %>
	<div>
	  <strong><%= comment.user_name %></strong>
	  <br />
	  <p><%= comment.body %><p>
	</div>
  <% end %>
  <%= render 'comments/form' %>
</p>

<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Editar', edit_idea_path(@idea) %></button> |
<button type="button" class="btn btn-primary btn-sm"><%= link_to 'Voltar', ideas_path %></button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.ico' %>
  <title>SINDEC CatalogoWeb</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container=fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://www.salvador.ba.gov.br" target="_blank">
        <img alt="Brand" src="http://www.sefaz.salvador.ba.gov.br/Imagens/logoPrefeitura.png">
      </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">Produtos</a></li>
      </ul>
      <a class="navbar-brand" href="/comments">Atributos</a>
            <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Buscar">
        </div>
        <button type="submit" class="btn btn-default">Ir</button>
      </form>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <button type="button" class="btn btn-default btn-sm"><%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %></button> |
            <button type="button" class="btn btn-default btn-sm"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></button>
          <% else %>
            <button type="button" class="btn btn-default btn-sm"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></button> |
            <button type="button" class="btn btn-default btn-sm"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %></button>
        </p>
    </div>
  </div>
</nav>

<div class="container">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>

<footer>
   <!-- <nav class="navbar navbar-inverse navbar-bottom">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">
            <!--<img alt="Brand" src="http://1.bp.blogspot.com/-thDwfG6U-40/U_X_3y90qgI/AAAAAAAAL9c/Prng7DIKBMA/s1600/SSA.png"> --> <!-- Desenvolvido por MaxTechnology para NTI-SINDEC 
          </a>
          <p class="navbar-text pull-right"> Desenvolvido por <a href="http://mdawis.wix.com/maxtechnology" target="_blank">MaxTechnology</a> para NTI - SINDEC.</p>
        </div>
      </div>
    </nav> -->

<nav class="navbar navbar-inverse navbar-bottom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div class="container">
      <a class="navbar-brand" href="#"><img alt="Brand" src="http://1.bp.blogspot.com/-thDwfG6U-40/U_X_3y90qgI/AAAAAAAAL9c/Prng7DIKBMA/s1600/SSA.png"></a>
    </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <div class="nav navbar-nav">
          <div class="container">
          <p class="navbar-text pull-right"> Desenvolvido por <a href="http://mdawis.wix.com/maxtechnology" target="_blank">MaxTechnology</a> para NTI - SINDEC.</p>
        </div>
        </div>
      </div><!-- /.navbar-collapse -->
    </div>
  </div><!-- /.container-fluid -->
</nav>

</footer>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="js/bootstrap.min.js"></script>


</body>
</html>